# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='optimization/messages/monitor.proto',
  package='optimization.messages.monitor',
  serialized_pb='\n#optimization/messages/monitor.proto\x12\x1doptimization.messages.monitor\"\x11\n\x0fRegisterMessage\"\x13\n\x11UnregisterMessage\"\x91\x03\n\x12MeasurementMessage\x12\x0c\n\x04time\x18\x01 \x02(\x01\x12\x42\n\x03\x63pu\x18\x02 \x03(\x0b\x32\x35.optimization.messages.monitor.MeasurementMessage.CPU\x12H\n\x06memory\x18\x03 \x02(\x0b\x32\x38.optimization.messages.monitor.MeasurementMessage.Memory\x1a\x81\x01\n\x06Memory\x12\r\n\x05total\x18\x01 \x02(\x04\x12\x0c\n\x04used\x18\x02 \x02(\x04\x12\x0c\n\x04\x66ree\x18\x03 \x02(\x04\x12\x0e\n\x06shared\x18\x04 \x02(\x04\x12\x0e\n\x06\x62uffer\x18\x05 \x02(\x04\x12\x0e\n\x06\x63\x61\x63hed\x18\x06 \x02(\x04\x12\x0c\n\x04user\x18\x07 \x02(\x04\x12\x0e\n\x06locked\x18\x08 \x02(\x04\x1a[\n\x03\x43PU\x12\r\n\x05total\x18\x01 \x02(\x04\x12\x0c\n\x04user\x18\x02 \x02(\x04\x12\x0c\n\x04nice\x18\x03 \x02(\x04\x12\x0b\n\x03sys\x18\x04 \x02(\x04\x12\x0c\n\x04idle\x18\x05 \x02(\x04\x12\x0e\n\x06iowait\x18\x06 \x02(\x04\"\x93\x02\n\x07Message\x12\x38\n\x04type\x18\x01 \x02(\x0e\x32*.optimization.messages.monitor.MessageType\x12@\n\x08register\x18\x02 \x01(\x0b\x32..optimization.messages.monitor.RegisterMessage\x12\x44\n\nunregister\x18\x03 \x01(\x0b\x32\x30.optimization.messages.monitor.UnregisterMessage\x12\x46\n\x0bmeasurement\x18\x04 \x01(\x0b\x32\x31.optimization.messages.monitor.MeasurementMessage*<\n\x0bMessageType\x12\x0c\n\x08Register\x10\x00\x12\x0e\n\nUnregister\x10\x01\x12\x0f\n\x0bMeasurement\x10\x02')

_MESSAGETYPE = descriptor.EnumDescriptor(
  name='MessageType',
  full_name='optimization.messages.monitor.MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='Register', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='Unregister', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='Measurement', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=792,
  serialized_end=852,
)


Register = 0
Unregister = 1
Measurement = 2



_REGISTERMESSAGE = descriptor.Descriptor(
  name='RegisterMessage',
  full_name='optimization.messages.monitor.RegisterMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=70,
  serialized_end=87,
)


_UNREGISTERMESSAGE = descriptor.Descriptor(
  name='UnregisterMessage',
  full_name='optimization.messages.monitor.UnregisterMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=89,
  serialized_end=108,
)


_MEASUREMENTMESSAGE_MEMORY = descriptor.Descriptor(
  name='Memory',
  full_name='optimization.messages.monitor.MeasurementMessage.Memory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='total', full_name='optimization.messages.monitor.MeasurementMessage.Memory.total', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='used', full_name='optimization.messages.monitor.MeasurementMessage.Memory.used', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='free', full_name='optimization.messages.monitor.MeasurementMessage.Memory.free', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='shared', full_name='optimization.messages.monitor.MeasurementMessage.Memory.shared', index=3,
      number=4, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='buffer', full_name='optimization.messages.monitor.MeasurementMessage.Memory.buffer', index=4,
      number=5, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cached', full_name='optimization.messages.monitor.MeasurementMessage.Memory.cached', index=5,
      number=6, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user', full_name='optimization.messages.monitor.MeasurementMessage.Memory.user', index=6,
      number=7, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='locked', full_name='optimization.messages.monitor.MeasurementMessage.Memory.locked', index=7,
      number=8, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=290,
  serialized_end=419,
)

_MEASUREMENTMESSAGE_CPU = descriptor.Descriptor(
  name='CPU',
  full_name='optimization.messages.monitor.MeasurementMessage.CPU',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='total', full_name='optimization.messages.monitor.MeasurementMessage.CPU.total', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user', full_name='optimization.messages.monitor.MeasurementMessage.CPU.user', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='nice', full_name='optimization.messages.monitor.MeasurementMessage.CPU.nice', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sys', full_name='optimization.messages.monitor.MeasurementMessage.CPU.sys', index=3,
      number=4, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='idle', full_name='optimization.messages.monitor.MeasurementMessage.CPU.idle', index=4,
      number=5, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='iowait', full_name='optimization.messages.monitor.MeasurementMessage.CPU.iowait', index=5,
      number=6, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=421,
  serialized_end=512,
)

_MEASUREMENTMESSAGE = descriptor.Descriptor(
  name='MeasurementMessage',
  full_name='optimization.messages.monitor.MeasurementMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='time', full_name='optimization.messages.monitor.MeasurementMessage.time', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cpu', full_name='optimization.messages.monitor.MeasurementMessage.cpu', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='memory', full_name='optimization.messages.monitor.MeasurementMessage.memory', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MEASUREMENTMESSAGE_MEMORY, _MEASUREMENTMESSAGE_CPU, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=111,
  serialized_end=512,
)


_MESSAGE = descriptor.Descriptor(
  name='Message',
  full_name='optimization.messages.monitor.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='optimization.messages.monitor.Message.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='register', full_name='optimization.messages.monitor.Message.register', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='unregister', full_name='optimization.messages.monitor.Message.unregister', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='measurement', full_name='optimization.messages.monitor.Message.measurement', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=515,
  serialized_end=790,
)

_MEASUREMENTMESSAGE_MEMORY.containing_type = _MEASUREMENTMESSAGE;
_MEASUREMENTMESSAGE_CPU.containing_type = _MEASUREMENTMESSAGE;
_MEASUREMENTMESSAGE.fields_by_name['cpu'].message_type = _MEASUREMENTMESSAGE_CPU
_MEASUREMENTMESSAGE.fields_by_name['memory'].message_type = _MEASUREMENTMESSAGE_MEMORY
_MESSAGE.fields_by_name['type'].enum_type = _MESSAGETYPE
_MESSAGE.fields_by_name['register'].message_type = _REGISTERMESSAGE
_MESSAGE.fields_by_name['unregister'].message_type = _UNREGISTERMESSAGE
_MESSAGE.fields_by_name['measurement'].message_type = _MEASUREMENTMESSAGE
DESCRIPTOR.message_types_by_name['RegisterMessage'] = _REGISTERMESSAGE
DESCRIPTOR.message_types_by_name['UnregisterMessage'] = _UNREGISTERMESSAGE
DESCRIPTOR.message_types_by_name['MeasurementMessage'] = _MEASUREMENTMESSAGE
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE

class RegisterMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REGISTERMESSAGE
  
  # @@protoc_insertion_point(class_scope:optimization.messages.monitor.RegisterMessage)

class UnregisterMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UNREGISTERMESSAGE
  
  # @@protoc_insertion_point(class_scope:optimization.messages.monitor.UnregisterMessage)

class MeasurementMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Memory(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _MEASUREMENTMESSAGE_MEMORY
    
    # @@protoc_insertion_point(class_scope:optimization.messages.monitor.MeasurementMessage.Memory)
  
  class CPU(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _MEASUREMENTMESSAGE_CPU
    
    # @@protoc_insertion_point(class_scope:optimization.messages.monitor.MeasurementMessage.CPU)
  DESCRIPTOR = _MEASUREMENTMESSAGE
  
  # @@protoc_insertion_point(class_scope:optimization.messages.monitor.MeasurementMessage)

class Message(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MESSAGE
  
  # @@protoc_insertion_point(class_scope:optimization.messages.monitor.Message)

# @@protoc_insertion_point(module_scope)
